name: 'Deploy to Firebase Hosting preview channel'
on:
  pull_request:
    paths:
      - 'src/**'
      - 'static/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'CHANGELOG.md'

jobs:
  build:
    name: 'Build app'
    uses: ./.github/workflows/build-sveltekit.yml

  deploy:
    name: 'Deploy to Firebase'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      checks: write
      pull-requests: write
    outputs:
      url: ${{ steps.firebase-deploy.outputs.details_url }}
    steps:
      - uses: actions/checkout@v6

      - name: 'Download build artifact'
        uses: actions/download-artifact@v6
        with:
          name: 'build'
          path: './public'

      - name: 'Deploy preview channel'
        id: firebase-deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: the-easy-link
          expires: '2d'
